// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBottomPopup: typeof import('./src/components/AppBottomPopup.vue')['default']
    AppEmpty: typeof import('./src/components/AppEmpty.vue')['default']
    AppNumTransition: typeof import('./src/components/AppNumTransition.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    AppSvgaPlayer: typeof import('./src/components/AppSvgaPlayer.vue')['default']
    AppTitleBar: typeof import('./src/components/AppTitleBar.vue')['default']
    CommonSeting: typeof import('./src/components/CommonSeting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeStickmanView: typeof import('./src/components/ThreeStickmanView.vue')['default']
  }
}
